import {
  LayoutDashboard,
  Users,
  FileText,
  Pill,
  MessageSquare,
  CreditCard,
  Settings,
} from "lucide-react";

// export const SIDEBAR_MENU = {
//   admin: [
//     {
//       label: "Dashboard",
//       icon: LayoutDashboard,
//       //   path: "/admin",
//     },
//     {
//       label: "Users",
//       icon: Users,
//       //   path: "/admin/users",
//     },
//     {
//       label: "Reports",
//       icon: FileText,
//       //   path: "/admin/reports",
//     },
//     {
//       label: "Settings",
//       icon: Settings,
//       //   path: "/admin/settings",
//     },
//   ],

//   doctor: [
//     {
//       label: "Dashboard",
//       icon: LayoutDashboard,
//         path: "/doctor",
//     },
//     {
//       label: "Patients",
//       icon: Users,
//         path: "/doctor/patients",
//     },
//     {
//       label: "Prescriptions",
//       icon: Pill,
//         path: "/doctor/prescriptions",
//     },
//     {
//       label: "Messages",
//       icon: MessageSquare,
//       //   path: "/doctor/messages",
//     },
//   ],

//   patient: [
//     {
//       label: "Dashboard",
//       icon: LayoutDashboard,
//       //   path: "/patient",
//     },
//     {
//       label: "My Records",
//       icon: FileText,
//       //   path: "/patient/records",
//     },
//     {
//       label: "Billing",
//       icon: CreditCard,
//       //   path: "/patient/billing",
//     },
//     {
//       label: "Prescriptions",
//       icon: Pill,
//       //   path: "/patient/prescriptions",
//     },
//     {
//       label: "Messages",
//       icon: MessageSquare,
//       //   path: "/patient/messages",
//     },
//     {
//       label: "Settings",
//       icon: Settings,
//       //   path: "/patient/settings",
//     },
//   ],
// };

export const SIDEBAR_MENU = {
  admin: [
    {
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/admin/dashboard",
    },
    {
      label: "Approve Doctors",
      icon: Users,
      path: "/admin/approve-doctors",
    },
    {
      label: "Doctors",
      icon: Users,
      path: "/admin/doctors",
    },
    {
      label: "Billing",
      icon: CreditCard,
      path: "/admin/billing",
    },
    // {
    //   label: "Users",
    //   icon: Users,
    //   path: "/admin/users",
    // },
    // Removed "Reports" link that pointed to deleted appointment page
    // {
    //   label: "Settings",
    //   icon: Settings,
    //   path: "/admin/settings",
    // },
  ],

  doctor: [
    {
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/doctor/dashboard",
    },
    {
      label: "Patients",
      icon: Users,
      path: "/doctor/patients",
    },
    {
      label: "Prescriptions",
      icon: Pill,
      path: "/doctor/prescriptions",
    },
    {
      label: "Messages",
      icon: MessageSquare,
      path: "/doctor/messages",
    },
  ],

  patient: [
    {
      label: "Dashboard",
      icon: LayoutDashboard,
      path: "/patient/dashboard",
    },
    {
      label: "My Records",
      icon: FileText,
      path: "/patient/records",
    },
    {
      label: "Billing",
      icon: CreditCard,
      path: "/patient/billing",
    },
    {
      label: "Prescriptions",
      icon: Pill,
      path: "/patient/prescriptions",
    },
    {
      label: "Messages",
      icon: MessageSquare,
      path: "/patient/messages",
    },
    {
      label: "Settings",
      icon: Settings,
      path: "/patient/settings",
    },
  ],
};
// export const user = {
//   id: 1,
//   name: "Ali Khan",
//   email: "ali.khan@hospital.com",
//   role: "doctor", // admin | doctor | patient
//   avatar: null, // optional
// };

export const appointments = [
  {
    id: 1,
    title: "Annual Physical Exam",
    time: "Mon, Oct 28, 2024 - 10:30 AM",
    doctor: "Dr. Evelyn Reed (Cardiology)",
    status: "Confirmed",
    statusColor: "green",
    type: "In-Clinic",
    showActions: true,
  },
  {
    id: 2,
    title: "Follow-up Consultation",
    time: "Wed, Nov 06, 2024 - 2:00 PM",
    doctor: "Dr. Ben Carter (Dermatology)",
    status: "Pending Confirmation",
    statusColor: "yellow",
    type: "Online",
    online: true,
    showActions: true,
  },
  {
    id: 3,
    title: "Dermatology Check-up",
    time: "Fri, Nov 15, 2024 - 9:00 AM",
    doctor: "Dr. Chloe Davis (Dermatology)",
    status: "Cancelled by Clinic",
    statusColor: "red",
    cancelled: true,
  },
];

export const MOCK_DOCTORS = [
  {
    id: 1,
    name: "Prof. Dr. Umber Jalil Bakhtiar",
    specialty: "Gynecologist",
    qualifications: "MBBS, MCPS, FCPS (Obstetrics & Gynecology)",
    reviews: "1,932",
    experience: "22+",
    satisfaction: "96%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: [
      "Pregnancy",
      "Hormonal Issues",
      "Gynecology",
      "Infertility",
      "Women's Health",
    ],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 2,000",
        fast: true,
        highlight: true,
      },
      {
        type: "hospital",
        title: "Quaid-E-Azam International Hospital",
        subtitle: "Islamabad",
        price: "Rs. 4,100",
        fast: true,
      },
    ],
  },
  {
    id: 2,
    name: "Dr. Kamran Ahmed",
    specialty: "Cardiologist",
    qualifications: "MBBS, FCPS (Cardiology), MRCP (UK)",
    reviews: "850",
    experience: "15+",
    satisfaction: "98%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Heart Attack", "Hypertension", "Eco Cardiography", "Heart Center"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Tomorrow",
        price: "Rs. 2,500",
        fast: false,
        highlight: true,
      },
      {
        type: "hospital",
        title: "Shifa International Hospital",
        subtitle: "Islamabad",
        price: "Rs. 5,000",
        fast: true,
      },
    ],
  },
  {
    id: 3,
    name: "Dr. Sarah Khan",
    specialty: "Dermatologist",
    qualifications: "MBBS, MD (Dermatology)",
    reviews: "1,200",
    experience: "10+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1594824812397-2372cff5e541?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Acne", "Skin Allergy", "Laser Therapy", "Skin Clinic"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 1,500",
        fast: true,
        highlight: true,
      },
      {
        type: "hospital",
        title: "Skin Care Clinic",
        subtitle: "Lahore",
        price: "Rs. 3,000",
        fast: false,
      },
    ],
  },
  {
    id: 4,
    name: "Dr. Faisal Mahmood",
    specialty: "Infectious Disease Specialist",
    qualifications:
      "MBBS, ABIM (Internal Medicine), ABIM (Infectious Diseases)",
    reviews: "560",
    experience: "18+",
    satisfaction: "99%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["COVID-19", "Fever", "Vaccination", "Infection Control"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 3,000",
        fast: true,
        highlight: true,
      },
      {
        type: "hospital",
        title: "Agha Khan University Hospital",
        subtitle: "Karachi",
        price: "Rs. 5,000",
        fast: true,
      },
    ],
  },
  {
    id: 5,
    name: "Dr. Maria Zafar",
    specialty: "Pediatrician",
    qualifications: "MBBS, FCPS (Pediatrics)",
    reviews: "920",
    experience: "12+",
    satisfaction: "97%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: [
      "Childhood Nutrition",
      "Vaccination",
      "Growth Issues",
      "Children Care",
    ],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Tomorrow",
        price: "Rs. 1,800",
        fast: false,
        highlight: true,
      },
      {
        type: "hospital",
        title: "Children Hospital",
        subtitle: "Lahore",
        price: "Rs. 2,500",
        fast: true,
      },
    ],
  },
  {
    id: 6,
    name: "Dr. Ahmed Ali",
    specialty: "Orthopedic Surgeon",
    qualifications: "MBBS, FRCS (Orthopedics)",
    reviews: "450",
    experience: "20+",
    satisfaction: "95%",
    image:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Joint Replacement", "Fractures", "Sports Injury", "Bone & Joint"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 2,200",
        fast: true,
      },
      {
        type: "hospital",
        title: "Mayo Hospital",
        subtitle: "Lahore",
        price: "Rs. 3,500",
        fast: true,
      },
    ],
  },
  {
    id: 7,
    name: "Dr. Sana Malik",
    specialty: "Neurologist",
    qualifications: "MBBS, MD (Neurology)",
    reviews: "670",
    experience: "14+",
    satisfaction: "92%",
    image:
      "https://images.unsplash.com/photo-1594824812397-2372cff5e541?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Migraine", "Stroke", "Epilepsy", "Brain & Nerve"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 2,800",
        fast: true,
      },
      {
        type: "hospital",
        title: "Kulsum International Hospital",
        subtitle: "Islamabad",
        price: "Rs. 4,500",
        fast: false,
      },
    ],
  },
  {
    id: 8,
    name: "Dr. Usman Raza",
    specialty: "Ophthalmologist",
    qualifications: "MBBS, FCPS (Ophthalmology)",
    reviews: "320",
    experience: "16+",
    satisfaction: "90%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Cataract Surgery", "LASIK", "Glaucoma", "Eye Care"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 1,200",
        fast: true,
      },
      {
        type: "hospital",
        title: "LRBT Eye Hospital",
        subtitle: "Karachi",
        price: "Rs. 2,000",
        fast: true,
      },
    ],
  },
  {
    id: 9,
    name: "Dr. Hina Yusuf",
    specialty: "Psychiatrist",
    qualifications: "MBBS, FCPS (Psychiatry)",
    reviews: "510",
    experience: "11+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Anxiety", "Depression", "Counselling", "Mental Health"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Today",
        price: "Rs. 2,500",
        fast: true,
      },
      {
        type: "hospital",
        title: "Mind & Soul Clinic",
        subtitle: "Islamabad",
        price: "Rs. 4,000",
        fast: false,
      },
    ],
  },
  {
    id: 10,
    name: "Dr. Bilal Siddiqui",
    specialty: "ENT Specialist",
    qualifications: "MBBS, DLO, FCPS (ENT)",
    reviews: "280",
    experience: "13+",
    satisfaction: "89%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Sinusitis", "Hearing Loss", "Tonsillitis", "ENT Clinic"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Available Tomorrow",
        price: "Rs. 1,600",
        fast: true,
      },
      {
        type: "hospital",
        title: "Ziauddin Hospital",
        subtitle: "Karachi",
        price: "Rs. 3,000",
        fast: true,
      },
    ],
  },
  {
    id: 11,
    name: "Dr. Ali Hamza",
    specialty: "Urologist",
    qualifications: "MBBS, FCPS (Urology)",
    reviews: "150",
    experience: "9+",
    satisfaction: "91%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Kidney Center", "Bladder Issues", "Urology"],
    consultations: [
      {
        type: "hospital",
        title: "City Hospital",
        subtitle: "Lahore",
        price: "Rs. 2,500",
        fast: true,
      },
    ],
  },
  {
    id: 12,
    name: "Dr. Noreen Shah",
    specialty: "Gynecologist",
    qualifications: "MBBS, FCPS",
    reviews: "890",
    experience: "15+",
    satisfaction: "96%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Women's Health", "Infertility", "Pregnancy"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Online",
        price: "Rs. 3,000",
        fast: true,
      },
    ],
  },
  {
    id: 13,
    name: "Dr. Junaid Khan",
    specialty: "Cardiologist",
    qualifications: "MBBS, FCPS",
    reviews: "600",
    experience: "18+",
    satisfaction: "97%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Heart Center", "Hypertension", "Cardiology"],
    consultations: [
      {
        type: "hospital",
        title: "Heart Institute",
        subtitle: "Faisalabad",
        price: "Rs. 4,500",
        fast: true,
      },
    ],
  },
  {
    id: 14,
    name: "Dr. Amna Batool",
    specialty: "Pediatrician",
    qualifications: "MBBS, MCPS",
    reviews: "420",
    experience: "7+",
    satisfaction: "93%",
    image:
      "https://images.unsplash.com/photo-1594824812397-2372cff5e541?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Children Care", "Vaccination", "Paediatrics"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Online",
        price: "Rs. 1,500",
        fast: true,
      },
    ],
  },
  {
    id: 15,
    name: "Dr. Zubair Shah",
    specialty: "Orthopedic",
    qualifications: "MBBS, FCPS",
    reviews: "750",
    experience: "22+",
    satisfaction: "95%",
    image:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Bone & Joint", "Joint Replacement", "Orthopaedics"],
    consultations: [
      {
        type: "hospital",
        title: "HMC",
        subtitle: "Peshawar",
        price: "Rs. 5,000",
        fast: true,
      },
    ],
  },
  {
    id: 16,
    name: "Dr. Fatima Noor",
    specialty: "Dermatologist",
    qualifications: "MBBS, MD",
    reviews: "300",
    experience: "10+",
    satisfaction: "90%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Skin Clinic", "Acne", "Dermatology"],
    consultations: [
      {
        type: "hospital",
        title: "Bolan Hospital",
        subtitle: "Quetta",
        price: "Rs. 3,500",
        fast: true,
      },
    ],
  },
  {
    id: 17,
    name: "Dr. Raza Abbas",
    specialty: "Neurologist",
    qualifications: "MBBS, FCPS",
    reviews: "580",
    experience: "16+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Brain & Nerve", "Stroke", "Neurology"],
    consultations: [
      {
        type: "hospital",
        title: "Civil Hospital",
        subtitle: "Sialkot",
        price: "Rs. 4,000",
        fast: true,
      },
    ],
  },
  {
    id: 18,
    name: "Dr. Maham Khan",
    specialty: "Ophthalmologist",
    qualifications: "MBBS, FCPS",
    reviews: "210",
    experience: "12+",
    satisfaction: "92%",
    image:
      "https://images.unsplash.com/photo-1594824812397-2372cff5e541?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Eye Care", "Glaucoma", "Ophthalmology"],
    consultations: [
      {
        type: "hospital",
        title: "DHO",
        subtitle: "Gujranwala",
        price: "Rs. 2,800",
        fast: true,
      },
    ],
  },
  {
    id: 19,
    name: "Dr. Waqar Younis",
    specialty: "Psychiatrist",
    qualifications: "MBBS, FCPS",
    reviews: "490",
    experience: "14+",
    satisfaction: "95%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Mental Health", "Anxiety", "Psychiatry"],
    consultations: [
      {
        type: "video",
        title: "Video Consultation",
        subtitle: "Online",
        price: "Rs. 6,000",
        fast: true,
      },
    ],
  },
  {
    id: 20,
    name: "Dr. Sadia Rehman",
    specialty: "ENT Specialist",
    qualifications: "MBBS, FCPS",
    reviews: "180",
    experience: "8+",
    satisfaction: "88%",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71f153678e?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["ENT Clinic", "Sinusitis", "ENT"],
    consultations: [
      {
        type: "hospital",
        title: "Services Hospital",
        subtitle: "Lahore",
        price: "Rs. 2,200",
        fast: true,
      },
    ],
  },
  {
    id: 21,
    name: "Dr. Imran Tahir",
    specialty: "Gynecologist",
    qualifications: "MBBS, FCPS",
    reviews: "1100",
    experience: "20+",
    satisfaction: "96%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Women's Health", "Pregnancy", "Gynecology"],
    consultations: [
      {
        type: "hospital",
        title: "PIMS",
        subtitle: "Islamabad",
        price: "Rs. 5,500",
        fast: true,
      },
    ],
  },
  {
    id: 22,
    name: "Dr. Kamran Akmal",
    specialty: "Cardiologist",
    qualifications: "MBBS, FCPS",
    reviews: "720",
    experience: "15+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Heart Center", "Hypertension", "Cardiology"],
    consultations: [
      {
        type: "hospital",
        title: "PMC",
        subtitle: "Faisalabad",
        price: "Rs. 4,000",
        fast: true,
      },
    ],
  },
  {
    id: 23,
    name: "Dr. Babar Azam",
    specialty: "Pediatrician",
    qualifications: "MBBS, FCPS",
    reviews: "500",
    experience: "11+",
    satisfaction: "92%",
    image:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Children Care", "Nutrition", "Paediatrics"],
    consultations: [
      {
        type: "hospital",
        title: "Children Hospital",
        subtitle: "Lahore",
        price: "Rs. 3,000",
        fast: true,
      },
    ],
  },
  {
    id: 24,
    name: "Dr. Rizwan Ahmed",
    specialty: "Orthopedic",
    qualifications: "MBBS, FCPS",
    reviews: "380",
    experience: "13+",
    satisfaction: "90%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Bone & Joint", "Fractures", "Orthopaedics"],
    consultations: [
      {
        type: "hospital",
        title: "Nishtar Hospital",
        subtitle: "Multan",
        price: "Rs. 2,800",
        fast: true,
      },
    ],
  },
  {
    id: 25,
    name: "Dr. Shadab Khan",
    specialty: "Dermatologist",
    qualifications: "MBBS, MD",
    reviews: "250",
    experience: "9+",
    satisfaction: "89%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Skin Clinic", "Laser Therapy", "Dermatology"],
    consultations: [
      {
        type: "hospital",
        title: "LRH",
        subtitle: "Peshawar",
        price: "Rs. 4,200",
        fast: true,
      },
    ],
  },
  {
    id: 26,
    name: "Dr. Shaheen Shah",
    specialty: "Neurologist",
    qualifications: "MBBS, FCPS",
    reviews: "610",
    experience: "14+",
    satisfaction: "93%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Brain & Nerve", "Epilepsy", "Neurology"],
    consultations: [
      {
        type: "hospital",
        title: "Holy Family",
        subtitle: "Islamabad",
        price: "Rs. 5,000",
        fast: true,
      },
    ],
  },
  {
    id: 27,
    name: "Dr. Haris Rauf",
    specialty: "Ophthalmologist",
    qualifications: "MBBS, FCPS",
    reviews: "320",
    experience: "10+",
    satisfaction: "91%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Eye Care", "LASIK", "Ophthalmology"],
    consultations: [
      {
        type: "hospital",
        title: "General Hospital",
        subtitle: "Rawalpindi",
        price: "Rs. 1,800",
        fast: true,
      },
    ],
  },
  {
    id: 28,
    name: "Dr. Iftikhar Ahmed",
    specialty: "Psychiatrist",
    qualifications: "MBBS, FCPS",
    reviews: "840",
    experience: "17+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Mental Health", "Depression", "Psychiatry"],
    consultations: [
      {
        type: "hospital",
        title: "Jinnah Hospital",
        subtitle: "Karachi",
        price: "Rs. 3,500",
        fast: true,
      },
    ],
  },
  {
    id: 29,
    name: "Dr. Fakhar Zaman",
    specialty: "ENT Specialist",
    qualifications: "MBBS, FCPS",
    reviews: "450",
    experience: "12+",
    satisfaction: "92%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["ENT Clinic", "Tonsillitis", "ENT"],
    consultations: [
      {
        type: "hospital",
        title: "Civil Hospital",
        subtitle: "Quetta",
        price: "Rs. 2,600",
        fast: true,
      },
    ],
  },
  {
    id: 30,
    name: "Dr. Naseem Shah",
    specialty: "Urologist",
    qualifications: "MBBS, FCPS",
    reviews: "190",
    experience: "8+",
    satisfaction: "90%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Kidney Center", "Urinary Issues", "Urology"],
    consultations: [
      {
        type: "hospital",
        title: "CMH",
        subtitle: "Multan",
        price: "Rs. 3,200",
        fast: true,
      },
    ],
  },
  {
    id: 31,
    name: "Dr. Sarfaraz Ahmed",
    specialty: "Gynecologist",
    qualifications: "MBBS, FCPS",
    reviews: "1500",
    experience: "25+",
    satisfaction: "97%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Women's Health", "Infertility", "Gynecology"],
    consultations: [
      {
        type: "hospital",
        title: "Sheikh Zayed",
        subtitle: "Lahore",
        price: "Rs. 6,500",
        fast: true,
      },
    ],
  },
  {
    id: 32,
    name: "Dr. Misbah-ul-Haq",
    specialty: "Cardiologist",
    qualifications: "MBBS, FCPS",
    reviews: "900",
    experience: "20+",
    satisfaction: "96%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Heart Center", "Eco Cardiography", "Cardiology"],
    consultations: [
      {
        type: "hospital",
        title: "NICVD",
        subtitle: "Karachi",
        price: "Rs. 8,000",
        fast: true,
      },
    ],
  },
  {
    id: 33,
    name: "Dr. Shahid Afridi",
    specialty: "Pediatrician",
    qualifications: "MBBS, FCPS",
    reviews: "1200",
    experience: "18+",
    satisfaction: "98%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Children Care", "Vaccination", "Paediatrics"],
    consultations: [
      {
        type: "hospital",
        title: "Lady Reading",
        subtitle: "Peshawar",
        price: "Rs. 4,500",
        fast: true,
      },
    ],
  },
  {
    id: 34,
    name: "Dr. Shoaib Malik",
    specialty: "Orthopedic",
    qualifications: "MBBS, FCPS",
    reviews: "600",
    experience: "16+",
    satisfaction: "94%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Bone & Joint", "Joint Replacement", "Orthopaedics"],
    consultations: [
      {
        type: "hospital",
        title: "Shifa",
        subtitle: "Islamabad",
        price: "Rs. 5,000",
        fast: true,
      },
    ],
  },
  {
    id: 35,
    name: "Dr. Saeed Ajmal",
    specialty: "Dermatologist",
    qualifications: "MBBS, MD",
    reviews: "400",
    experience: "12+",
    satisfaction: "92%",
    image:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Skin Clinic", "Acne", "Dermatology"],
    consultations: [
      {
        type: "hospital",
        title: "Ganga Ram",
        subtitle: "Lahore",
        price: "Rs. 3,500",
        fast: true,
      },
    ],
  },
  {
    id: 36,
    name: "Dr. Mohammad Yousuf",
    specialty: "Neurologist",
    qualifications: "MBBS, FCPS",
    reviews: "800",
    experience: "22+",
    satisfaction: "95%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Brain & Nerve", "Stroke", "Neurology"],
    consultations: [
      {
        type: "hospital",
        title: "Agha Khan",
        subtitle: "Karachi",
        price: "Rs. 7,000",
        fast: true,
      },
    ],
  },
  {
    id: 37,
    name: "Dr. Inzamam-ul-Haq",
    specialty: "Ophthalmologist",
    qualifications: "MBBS, FCPS",
    reviews: "1000",
    experience: "20+",
    satisfaction: "96%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Eye Care", "Cataract Surgery", "Ophthalmology"],
    consultations: [
      {
        type: "hospital",
        title: "Gulab Devi",
        subtitle: "Lahore",
        price: "Rs. 5,500",
        fast: true,
      },
    ],
  },
  {
    id: 38,
    name: "Dr. Wasim Akram",
    specialty: "Psychiatrist",
    qualifications: "MBBS, FCPS",
    reviews: "2000",
    experience: "25+",
    satisfaction: "99%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Mental Health", "Counselling", "Psychiatry"],
    consultations: [
      {
        type: "hospital",
        title: "Quid-e-Azam",
        subtitle: "Islamabad",
        price: "Rs. 10,000",
        fast: true,
      },
    ],
  },
  {
    id: 39,
    name: "Dr. Waqar Younis",
    specialty: "ENT Specialist",
    qualifications: "MBBS, FCPS",
    reviews: "1800",
    experience: "24+",
    satisfaction: "97%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["ENT Clinic", "Sinusitis", "ENT"],
    consultations: [
      {
        type: "hospital",
        title: "Jinnah",
        subtitle: "Lahore",
        price: "Rs. 8,500",
        fast: true,
      },
    ],
  },
  {
    id: 40,
    name: "Dr. Moin Khan",
    specialty: "Urologist",
    qualifications: "MBBS, FCPS",
    reviews: "600",
    experience: "15+",
    satisfaction: "91%",
    image:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=80",
    isVerified: true,
    tags: ["Kidney Center", "Urinary Issues", "Urology"],
    consultations: [
      {
        type: "hospital",
        title: "LNH",
        subtitle: "Karachi",
        price: "Rs. 4,000",
        fast: true,
      },
    ],
  },
];
